[package]
description = "Orson Peters' personal crate"
name = "orlp"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/orlp/orlp-crate"
readme = "README.md"
license = "Zlib"

[dependencies]


