[package]
description = "Orson Peters' personal crate"
name = "orlp"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/orlp/orlp-crate"
readme = "README.md"
license = "Zlib"

[features]
default = ["std"]
unstable = []
std = []

[dependencies]